name: dart_style
version: 0.1.0-dev
author: Dart Team <misc@dartlang.org>
description: Opinionated, automatic Dart source code formatter.
homepage: https://github.com/dart-lang/dart_style
dependencies:
  analyzer: '>=0.22.0 <0.23.0'
  args: '>=0.12.1 <0.13.0'
  path: '>=1.0.0 <2.0.0'
  source_span: '>=1.0.0 <2.0.0'
dev_dependencies:
  browser: '>=0.10.0 <0.11.0'
  scheduled_test: '>=0.11.2 <0.12.0'
  unittest: '>=0.11.0 <0.12.0'
executables:
  dartformat: format
